### ISSUE TITLE
Titre Questel : Le titre affiche le chemin XML 

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#1]
Il faudra mettre le numéro de brevet comme titre si aucun titre ne peux être extrait des sources
![image](https://cloud.githubusercontent.com/assets/11230930/6777638/b40056c4-d14b-11e4-8dfe-b760368f8671.png)

**Comment by Ludovic-Romano** [comment]
Corrigé en DEV:
![bug](https://cloud.githubusercontent.com/assets/11611048/6778641/b20a0028-d154-11e4-946e-f7d42a3fec19.jpg)
