### ISSUE TITLE
Page trends - les graphiques ne présentent pas toutes les dates

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#10]
Les années vides ne sont pas représenté, du coup l’échelle de temps n'est pas linéaire.
Le moteur devra être réglé pour généré les valeurs vides.
![image](https://cloud.githubusercontent.com/assets/11230930/6778856/ae988cfa-d156-11e4-83d4-15ab733a416e.png)

**Comment by Ludovic-Romano** [comment]
Evolution apportée en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6804522/74a8d430-d23e-11e4-95c2-1e4c3ce8006d.jpg)

![bugb](https://cloud.githubusercontent.com/assets/11611048/6804535/8a3ef040-d23e-11e4-9a92-25b2d6f784d4.jpg)


Modification apportées :
- création d'une search logic spécifique trends "sl_trends"
- Ajout d'une facette dynamique date

Bug observé :
Le drill down année > Mois > jour ne fonctionne par très bien, il semble sauter certains niveaux, il passe directement de année à mois si on coche "day" dans la config de la facette. et si on décoche day on ne peu descendre au jour
