### ISSUE TITLE
Relier page résultat et page trends

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#11]
Les recherches sur trends et résulats sont totalement deconnectées.
Il faut pemettre un passage de l'un à l'autre en conservant le contexte de recherche (paramètre q uniquement)

![image](https://cloud.githubusercontent.com/assets/11230930/6779082/9dcd1326-d158-11e4-8af9-e368b55cbe12.png)

![image](https://cloud.githubusercontent.com/assets/11230930/6779107/d4510baa-d158-11e4-82e7-f63b07816207.png)

Style visible sur la page contact du site .com

**Comment by Ludovic-Romano** [comment]
Evolution apportée en DEV :
- Page de résultat :
![bug](https://cloud.githubusercontent.com/assets/11611048/6798618/381d219e-d20f-11e4-9b22-14847dd786fc.jpg)

- Page trends :
![bugb](https://cloud.githubusercontent.com/assets/11611048/6798623/48b73b52-d20f-11e4-81c7-64a63a5306ae.jpg)
