### ISSUE TITLE
Page résultat - nombre de résultats max : 10000

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#12]
Le nombre de résultat par requête maxi doit passer  à 10 000.
Si le résultat est 10000 afficher la phrase
1-10 of more than 10 000

![image](https://cloud.githubusercontent.com/assets/11230930/6781422/d05dfb2e-d16d-11e4-89b3-750622b5915d.png)

**Comment by Ludovic-Romano** [comment]
Corrigé en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6783523/5ee6f344-d17a-11e4-87b7-05a0b4d9199b.jpg)

Modifications apportée :
- Limitation du nombre de résultats search logic et feed mashup (page search)
- Modification jsp widget navigation header : ajout d'un test en dur
