### ISSUE TITLE
Le header est positionné sur la preview

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#14]
![image](https://cloud.githubusercontent.com/assets/11230930/6781968/763b6b6e-d171-11e4-9705-f7dde62d4b4f.png)

**Comment by Ludovic-Romano** [comment]
Corrigé en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6783773/f10f0652-d17b-11e4-9190-5545efac9da4.jpg)

Modifications apportées :
- Modification css du widget preview : modification des z-index
