### ISSUE TITLE
Ne pas indexé les fichiers système

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#15]
Il faudrait pouvoir supprimer les fichiers systèmes de l'indexation

les ~$nom_du_fichier que Windows crée quand un document office est ouvert 

![image](https://cloud.githubusercontent.com/assets/11230930/6782083/425403e6-d172-11e4-8215-07ac98d812a3.png)

**Comment by Ludovic-Romano** [comment]
Corrigé en DEV :
- Avant modification :
![bugb](https://cloud.githubusercontent.com/assets/11611048/6783348/8dd92af6-d179-11e4-8c16-75381a147f89.jpg)

- Après modification :
![bug](https://cloud.githubusercontent.com/assets/11611048/6783365/9b547ff0-d179-11e4-985d-50479efc73cc.jpg)

- Modification apportées :
Exclusion des fichiers (path) contenat un tilde "~" pour toutes les sources de type file
