### ISSUE TITLE
Sous facettes origin pour Filer Issoire

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#16]
Créer des sous facets origin pour chacun des repertoires indexé :

Répertoires:
\\issfiler01\SITE\Bibliotheque des consignes\Qualite\En Application
\\Issfiler01\secteurs\SMQ\Basede\DEDOC
\\issfiler01\SITE\Qualité\Documentation Externe

Sous-facettes:
-          Plant practices
-          Product specifications
-          Issoire technical reports

**Comment by Ludovic-Romano** [comment]
Evolution mise en oeuvre en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6803404/8f2415b0-d237-11e4-966c-37e25b36e252.jpg)
