### ISSUE TITLE
Bloc 174-223MHZ manquant

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#18]
Le bloc existe sur l'index (api console : frise_bandefrequence_freq_min:174000000) mais pas généré sur le frise:
![image](https://cloud.githubusercontent.com/assets/11230930/6851368/e7b91416-d3de-11e4-8a30-3d3cf22a19b7.png)

**Comment by Ludovic-Romano** [comment]
A déplacer dans le projet ANFR
