### ISSUE TITLE
Filers : pas de lien sur le titre ni l'image

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#2]
Il faut que l'image et le titre mène au téléchargement du document de la même manière que le lien download
![image](https://cloud.githubusercontent.com/assets/11230930/6777722/95137394-d14c-11e4-81f8-806e9e3c5be4.png)

**Comment by Ludovic-Romano** [comment]
Evolution apportée en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6801836/9225b45a-d22b-11e4-8b6c-a39db7257f28.jpg)
