### ISSUE TITLE
Popup détail - texte trop court

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#3]
Depuis la dernière MEP, l'extrait de texte sur la popup est trop court, il faut revenir au niveau d'avant
![image](https://cloud.githubusercontent.com/assets/11230930/6777846/ccab9c68-d14d-11e4-9eff-ac195ac7be8e.png)

**Comment by Ludovic-Romano** [comment]
Regression ibservée en DEV corrigée (search logic définie dans les feeds) :
![bug](https://cloud.githubusercontent.com/assets/11611048/6799746/a09d1964-d218-11e4-8d25-0fc1ffd9b265.jpg)
