### ISSUE TITLE
Taxonomie - charger les nouveaux fichier

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#4]
Nous disposons de nouveaux fichiers de taxonomie sur le SVN (Materials and Aluminum for Constellium.zip)

Il faut les charger dans le pipeline

**Comment by Ludovic-Romano** [comment]
Nouvelle taxonomy chargée :
- Taxonomy composée de 4 fichiers : Engineering_Materials_Properties.xml, Engineering_Materials_Processing.xml, Metallurgy_Metal_Manufacturing.xml,Metals_Aluminum.xml
- Corrections apportées aux fichiers xml : lang "fr-CA" passée en "fr", nom des packages modifiés, balise root modifiée afin dêtre dans le bon format.

rendu :
![bug](https://cloud.githubusercontent.com/assets/11611048/6820604/ff98b60e-d2d0-11e4-85d5-b4fe2213c512.jpg)
