### ISSUE TITLE
Image triangle sur fond blanc

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#5]
Le triangle bleu a un fond blanc ce qui pose problème sur certains éléments à fond gris, il faudrait utiliser la transparence.

![image](https://cloud.githubusercontent.com/assets/11230930/6778019/3fb33fa8-d14f-11e4-978a-660bf8ee3a7e.png)

**Comment by Ludovic-Romano** [comment]
Corrigé en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6780003/a4abab40-d161-11e4-8234-8ef4dd7afd69.jpg)
