### ISSUE TITLE
Dates des documents Elsevier

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#6]
Les dates indiqués sur le moteur ne correspondent aux dates réelles.
![image](https://cloud.githubusercontent.com/assets/11230930/6778091/11eb163a-d150-11e4-81e1-230f567f497c.png)

**Comment by Ludovic-Romano** [comment]
pour l'instant c'est non reproductible.
Il faudrait que je puisse récupérer le fichier xml source d'un document qui présente l'anomalie.
le problème est que l'on ne peut pas identifier l'archive source du document

**Comment by Pierre-Morlet** [comment]
Vu avec le client, les XML ne comportent que les années. On va garder le 1er janvier pour l'instant.
