### ISSUE TITLE
Ajouter le titre comme critère de tri

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#7]
Rajouter Title comme option de tri
![image](https://cloud.githubusercontent.com/assets/11230930/6778137/7b3dd668-d150-11e4-8443-1da48454d8e0.png)

**Comment by Ludovic-Romano** [comment]
Evolution apportée en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6799444/313ff2c8-d216-11e4-9bf8-1d65e89ff306.jpg)

Remarque : Seule la source elsevier a été réindexée !
