### ISSUE TITLE
Liste de résultats - afficher la facette origin pour les filers et les sites

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#8]
Il faut afficher la source pour les documents issus des filers et de sites.
note: non visible en mode d'affichage réduit
![image](https://cloud.githubusercontent.com/assets/11230930/6778340/2c204ee2-d152-11e4-9aa6-4d0282cb15de.png)

**Comment by Ludovic-Romano** [comment]
ajouté en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6782788/7b351502-d176-11e4-91ed-fc814476b666.jpg)

Information supplémentaires :
- Ajouté sur toutes les sources
- liens cliquables pour refinement

**Comment by Pierre-Morlet** [comment]
Il ne faut pas l'afficher pour Questel , juste les filers et les sites

**Comment by Pierre-Morlet** [comment]
en attente de validation client

**Comment by Pierre-Morlet** [comment]
L'affichage est bon , par contre il faut désactivé les liens pour refinement

**Comment by Ludovic-Romano** [comment]
Modification apportée en DEV :
- Page de résultat :
![bugb](https://cloud.githubusercontent.com/assets/11611048/6798922/12acdbd6-d212-11e4-8c84-9cdabca3fe49.jpg)

- Page de détails : L'origine est affichée en facette et plus en meta :
![bug](https://cloud.githubusercontent.com/assets/11611048/6798923/1800cf84-d212-11e4-8f62-144ae0006cd9.jpg)
