### ISSUE TITLE
Page stats : Nombres trop proches du bord de la colonne

### ISSUE THREAD

**Issue by Pierre-Morlet** [Pierre-Morlet/CONSTEL#9]
Les nombres de la colonnes en rouge sont trop proches du bord et déborde en cas de grands nombres (phénomène constaté par le client) 
![image](https://cloud.githubusercontent.com/assets/11230930/6778759/be5e849c-d155-11e4-80b3-02d1e7f74e1a.png)

**Comment by Ludovic-Romano** [comment]
Corrigé en DEV :
![bug](https://cloud.githubusercontent.com/assets/11611048/6780055/1cd00206-d162-11e4-84d9-197c615770eb.jpg)
